version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: pfe-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: pfe-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongodb

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: pfe-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./backend/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  backend:
    build:
      context: ./backend
    container_name: pfe-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/pfe_iot
      JWT_SECRET: change_this_secret
      JWT_EXPIRES_IN: 7d
      MQTT_URL: mqtt://mosquitto:1883
      MQTT_CLIENT_ID: pfe-backend
      TEMP_HIGH: 45
      HUMIDITY_HIGH: 80
      BATTERY_LOW: 11
    depends_on:
      - mongodb
      - mosquitto

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    container_name: pfe-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
